//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int id { get; set; }
        public string name { get; set; }
        public int strength { get; set; }
        public int vitality { get; set; }
        public int intelligence { get; set; }
        public int imagination { get; set; }
        public int agility { get; set; }
        public int dexterity { get; set; }
        public int luck { get; set; }
        public int current_hp { get; set; }
        public int current_mp { get; set; }
        public int current_ap { get; set; }
        public int class_resource { get; set; }
        public int subclass_resource { get; set; }
        public string class_exp { get; set; }
        public string skill_ranks { get; set; }
        public int current_class_id { get; set; }
        public int current_subclass_id { get; set; }
        public string current_reactions { get; set; }
        public string current_passives { get; set; }
        public string current_movements { get; set; }
    }
}
