//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.CharacterLevels = new HashSet<CharacterLevel>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isMonster { get; set; }
        public Nullable<int> strength { get; set; }
        public Nullable<int> vitality { get; set; }
        public Nullable<int> intelligence { get; set; }
        public Nullable<int> imagination { get; set; }
        public Nullable<int> agility { get; set; }
        public Nullable<int> dexterity { get; set; }
        public Nullable<int> luck { get; set; }
        public Nullable<int> current_hp { get; set; }
        public Nullable<int> current_mp { get; set; }
        public Nullable<int> current_ap { get; set; }
        public Nullable<int> class_resource { get; set; }
        public Nullable<int> subclass_resource { get; set; }
        public Nullable<long> exp { get; set; }
        public Nullable<int> chara_level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterLevel> CharacterLevels { get; set; }
        public virtual Monster Monster { get; set; }
    }
}
