//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterLevel
    {
        public Nullable<int> chara_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string skill_levels { get; set; }
        public Nullable<long> exp { get; set; }
        public Nullable<int> current_level { get; set; }
        public int id { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Class Class { get; set; }
    }
}
