//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int id { get; set; }
        public string skill_ids { get; set; }
        public Nullable<double> strength { get; set; }
        public Nullable<double> vitality { get; set; }
        public Nullable<double> intelligence { get; set; }
        public Nullable<double> imagination { get; set; }
        public Nullable<double> agility { get; set; }
        public Nullable<double> dexterity { get; set; }
        public string name { get; set; }
    }
}
