//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.CharacterLevels = new HashSet<CharacterLevel>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int id { get; set; }
        public string skill_ids { get; set; }
        public Nullable<double> strength { get; set; }
        public Nullable<double> vitality { get; set; }
        public Nullable<double> intelligence { get; set; }
        public Nullable<double> imagination { get; set; }
        public Nullable<double> agility { get; set; }
        public Nullable<double> dexterity { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterLevel> CharacterLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
