//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionValue
    {
        public int id { get; set; }
        public Nullable<int> PC1 { get; set; }
        public Nullable<int> PC2 { get; set; }
        public Nullable<int> PC3 { get; set; }
        public Nullable<int> PC4 { get; set; }
        public Nullable<int> PC5 { get; set; }
        public Nullable<int> PC6 { get; set; }
    }
}
